name: link_vault
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+8


environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  hive: ^2.2.3
  html: ^0.15.4
  http: ^1.2.1
  path: ^1.8.0
  path_provider: ^2.1.3
  permission_handler: ^11.3.1

  # flutter_layout_grid: ^2.0.1
  flutter_riverpod: ^2.5.1
  flutter_staggered_grid_view: ^0.7.0
  receive_sharing_intent: ^1.4.5
  share_plus: ^9.0.0
  url_launcher: ^6.3.0

  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  fpdart: ^1.1.0
  hive_flutter: ^1.1.0
  firebase_core: ^3.1.0
  firebase_auth: ^5.1.0
  flutter_bloc: ^8.1.6
  flutter_svg: ^2.0.9
  cloud_firestore: ^5.0.2
  webview_flutter: ^4.8.0
  google_mobile_ads: ^5.1.0
  lottie: ^3.1.2
  image: ^4.2.0
  # html_unescape: ^2.0.0
  flutter_image_compress: ^2.3.0
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  # archive: ^3.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.9
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^4.0.0
  hive_generator: ^2.0.1
  rename: ^3.0.2
  very_good_analysis: ^5.1.0
  isar_generator: ^3.1.0+1
  

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
     - assets/images/
    #  - assets/fonts/
     - assets/logo/
     - assets/animations/


  # fonts:
  #   - family: Ubuntu
  #     fonts:
  #       - asset: assets/fonts/ubuntu/Ubuntu-Bold.ttf


flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo/abstract-link_512.png"

  remove_alpha_ios: true
  min_sdk_android: 21 # android min sdk min:16, default 21
  