name: web_link_store
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
#  image_picker: ^0.8.5+3
#  gallery_saver: ^2.3.2


  # database:
  hive: ^2.2.1
  riverpod: ^1.0.3
  flutter_riverpod: ^1.0.4
  hive_generator: ^1.1.3
  path: ^1.8.0
  path_provider: ^2.0.10
  permission_handler: ^9.2.0
  build_runner: ^2.1.11

 #for design_tools:
  flutter_inset_box_shadow: ^1.0.7
  flutter_staggered_grid_view: ^0.6.1
  flutter_layout_grid: ^2.0.1
  html: ^0.15.0
  http: ^0.13.4
  url_launcher: ^6.1.4
  webview_flutter: ^3.0.4
  receive_sharing_intent: ^1.4.5
  share_plus: ^4.0.10

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^1.0.0
  rename: ^3.0.2

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
     - assets/images/
     - assets/fonts/

  fonts:
    - family: Ubuntu
      fonts:
        - asset: assets/fonts/ubuntu/Ubuntu-Bold.ttf
        - asset: assets/fonts/ubuntu/Ubuntu-BoldItalic.ttf
        - asset: assets/fonts/ubuntu/Ubuntu-Italic.ttf
        - asset: assets/fonts/ubuntu/Ubuntu-Light.ttf
        - asset: assets/fonts/ubuntu/Ubuntu-LightItalic.ttf
        - asset: assets/fonts/ubuntu/Ubuntu-Medium.ttf
        - asset: assets/fonts/ubuntu/Ubuntu-MediumItalic.ttf
        - asset: assets/fonts/ubuntu/Ubuntu-Regular.ttf


flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  # image_path: "assets/logo/3d_link.png"
  image_path: "assets/logo/infinite_loop.jpg"

  # image_path: "assets/logo/green_spiral_with_background.jpg"

  remove_alpha_ios: true
  min_sdk_android: 21 # android min sdk min:16, default 21
  