// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'core/data/models/auth_settings_model.dart';
import 'features/collections/data/models/collection_model.dart';
import 'features/collections/data/models/search_history_model.dart';
import 'features/items/data/models/item_model.dart';
import 'features/settings/data/models/app_settings_model.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
      id: const obx_int.IdUid(1, 3712937077068604428),
      name: 'AppSettingsModel',
      lastPropertyId: const obx_int.IdUid(5, 1053603822047256309),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 2209342593238822856),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 7347789794011051129),
            name: 'lastAdWatch',
            type: 10,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 326058209068253710),
            name: 'isPremium',
            type: 1,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 535809320177100057),
            name: 'hasMigratedToCloud',
            type: 1,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 1053603822047256309),
            name: 'dbThemeMode',
            type: 6,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(2, 5849219588462393305),
      name: 'AuthSettingsModel',
      lastPropertyId: const obx_int.IdUid(11, 480709859896423710),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 2846338009472945797),
            name: 'id',
            type: 6,
            flags: 129),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 4827465255069710658),
            name: 'hasSeenOnboarding',
            type: 1,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 1059668868780102894),
            name: 'isGuestMode',
            type: 1,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 8695278132393047110),
            name: 'installDate',
            type: 10,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 6850893731177395455),
            name: 'lastAdWatchedAt',
            type: 10,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(6, 3623215960999661916),
            name: 'lastAdFailed',
            type: 1,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(7, 7278418656919357870),
            name: 'offlineGracePeriodStart',
            type: 10,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(8, 5289512684247903679),
            name: 'dayPassExpiresAt',
            type: 10,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(9, 2177515961368509429),
            name: 'isPremiumCached',
            type: 1,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(10, 3900409415605503935),
            name: 'hasMigratedToCloud',
            type: 1,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(11, 480709859896423710),
            name: 'themeMode',
            type: 9,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(3, 5730371926328866297),
      name: 'CollectionModel',
      lastPropertyId: const obx_int.IdUid(25, 1285019974657237596),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 1301829372740442991),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 4777222735186962361),
            name: 'uid',
            type: 9,
            flags: 2080,
            indexId: const obx_int.IdUid(1, 1820529652983650800)),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 1042854652956709266),
            name: 'ownerId',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 574791585606913701),
            name: 'isShared',
            type: 1,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 5453332528611644029),
            name: 'title',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(6, 7053081148233879503),
            name: 'category',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(7, 4820841968673638082),
            name: 'colorHex',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(8, 7792858474470365085),
            name: 'iconName',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(9, 8699486832562175477),
            name: 'position',
            type: 8,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(10, 5145296700179462546),
            name: 'createdAt',
            type: 10,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(11, 1669410262979459514),
            name: 'updatedAt',
            type: 10,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(12, 8128030011837012598),
            name: 'itemCount',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(13, 2634712499462882079),
            name: 'parentId',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(14, 5858540030880926328),
            name: 'isPinned',
            type: 1,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(15, 4579439767859949290),
            name: 'isArchived',
            type: 1,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(16, 4395960698390096293),
            name: 'isDeleted',
            type: 1,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(17, 3802886459136006474),
            name: 'childCount',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(18, 8982339870197124853),
            name: 'description',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(19, 9038032919751803621),
            name: 'iconJson',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(20, 2963113255417979106),
            name: 'itemsLayout',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(21, 9003180395958761994),
            name: 'itemsSortDefault',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(22, 8443699427568464173),
            name: 'openLinksIn',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(23, 5173186625873116228),
            name: 'showLinkPreviews',
            type: 1,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(24, 1155281046020825262),
            name: 'lastAccessedAt',
            type: 10,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(25, 1285019974657237596),
            name: 'childCollectionsLayout',
            type: 9,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(4, 328533937922981262),
      name: 'ItemModel',
      lastPropertyId: const obx_int.IdUid(30, 259879101094635734),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 3350982875288984299),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 2719751623722923038),
            name: 'uid',
            type: 9,
            flags: 2080,
            indexId: const obx_int.IdUid(2, 7297498146274015927)),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 3149462872452473471),
            name: 'ownerId',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 4513586168020500529),
            name: 'title',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 4548202439707431896),
            name: 'description',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(6, 4577251279909621259),
            name: 'imagePath',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(7, 1482225421024857713),
            name: 'imageUrl',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(8, 6805819360045786009),
            name: 'link',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(10, 6167179647945300023),
            name: 'tags',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(12, 6329644407112702688),
            name: 'dbStatus',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(13, 891141021799947655),
            name: 'collectionUid',
            type: 9,
            flags: 2048,
            indexId: const obx_int.IdUid(3, 6024706868027249757)),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(14, 2839185912509053998),
            name: 'position',
            type: 8,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(15, 2286213370297118386),
            name: 'createdAt',
            type: 10,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(16, 7092394482203611515),
            name: 'updatedAt',
            type: 10,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(17, 9014242142404849946),
            name: 'collectionId',
            type: 11,
            flags: 520,
            indexId: const obx_int.IdUid(4, 4471310188009959902),
            relationTarget: 'CollectionModel'),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(18, 3982830580985195947),
            name: 'annotation',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(19, 2297163299018166586),
            name: 'faviconUrl',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(20, 6580459291987530291),
            name: 'dominantColor',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(21, 3791120418302521793),
            name: 'siteName',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(22, 4812080865479975745),
            name: 'canonicalUrl',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(23, 6704937845926635303),
            name: 'contentType',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(24, 4238896887064578209),
            name: 'publishedAt',
            type: 10,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(25, 2671407846795417719),
            name: 'isPinned',
            type: 1,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(26, 6603623744955188865),
            name: 'clickCount',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(27, 4561958621040648625),
            name: 'lastAccessedAt',
            type: 10,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(28, 1484607773168578181),
            name: 'isDeleted',
            type: 1,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(29, 7717661519180054530),
            name: 'deletedAt',
            type: 10,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(30, 259879101094635734),
            name: 'openLinksInOverride',
            type: 9,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(5, 4726494674158433880),
      name: 'SearchHistoryModel',
      lastPropertyId: const obx_int.IdUid(3, 805015051994274526),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 8116658242244622687),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 7339821541894070905),
            name: 'query',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 805015051994274526),
            name: 'searchedAt',
            type: 10,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[])
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore(
    {String? directory,
    int? maxDBSizeInKB,
    int? maxDataSizeInKB,
    int? fileMode,
    int? maxReaders,
    bool queriesCaseSensitiveDefault = true,
    String? macosApplicationGroup}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(getObjectBoxModel(),
      directory: directory ?? (await defaultStoreDirectory()).path,
      maxDBSizeInKB: maxDBSizeInKB,
      maxDataSizeInKB: maxDataSizeInKB,
      fileMode: fileMode,
      maxReaders: maxReaders,
      queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
      macosApplicationGroup: macosApplicationGroup);
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
      entities: _entities,
      lastEntityId: const obx_int.IdUid(5, 4726494674158433880),
      lastIndexId: const obx_int.IdUid(4, 4471310188009959902),
      lastRelationId: const obx_int.IdUid(0, 0),
      lastSequenceId: const obx_int.IdUid(0, 0),
      retiredEntityUids: const [],
      retiredIndexUids: const [],
      retiredPropertyUids: const [210722606043499996, 93655818926627561],
      retiredRelationUids: const [],
      modelVersion: 5,
      modelVersionParserMinimum: 5,
      version: 1);

  final bindings = <Type, obx_int.EntityDefinition>{
    AppSettingsModel: obx_int.EntityDefinition<AppSettingsModel>(
        model: _entities[0],
        toOneRelations: (AppSettingsModel object) => [],
        toManyRelations: (AppSettingsModel object) => {},
        getId: (AppSettingsModel object) => object.id,
        setId: (AppSettingsModel object, int id) {
          object.id = id;
        },
        objectToFB: (AppSettingsModel object, fb.Builder fbb) {
          fbb.startTable(6);
          fbb.addInt64(0, object.id);
          fbb.addInt64(1, object.lastAdWatch?.millisecondsSinceEpoch);
          fbb.addBool(2, object.isPremium);
          fbb.addBool(3, object.hasMigratedToCloud);
          fbb.addInt64(4, object.dbThemeMode);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final lastAdWatchValue =
              const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 6);
          final object = AppSettingsModel()
            ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
            ..lastAdWatch = lastAdWatchValue == null
                ? null
                : DateTime.fromMillisecondsSinceEpoch(lastAdWatchValue)
            ..isPremium =
                const fb.BoolReader().vTableGet(buffer, rootOffset, 8, false)
            ..hasMigratedToCloud =
                const fb.BoolReader().vTableGet(buffer, rootOffset, 10, false)
            ..dbThemeMode =
                const fb.Int64Reader().vTableGet(buffer, rootOffset, 12, 0);

          return object;
        }),
    AuthSettingsModel: obx_int.EntityDefinition<AuthSettingsModel>(
        model: _entities[1],
        toOneRelations: (AuthSettingsModel object) => [],
        toManyRelations: (AuthSettingsModel object) => {},
        getId: (AuthSettingsModel object) => object.id,
        setId: (AuthSettingsModel object, int id) {
          object.id = id;
        },
        objectToFB: (AuthSettingsModel object, fb.Builder fbb) {
          final themeModeOffset = fbb.writeString(object.themeMode);
          fbb.startTable(12);
          fbb.addInt64(0, object.id);
          fbb.addBool(1, object.hasSeenOnboarding);
          fbb.addBool(2, object.isGuestMode);
          fbb.addInt64(3, object.installDate?.millisecondsSinceEpoch);
          fbb.addInt64(4, object.lastAdWatchedAt?.millisecondsSinceEpoch);
          fbb.addBool(5, object.lastAdFailed);
          fbb.addInt64(
              6, object.offlineGracePeriodStart?.millisecondsSinceEpoch);
          fbb.addInt64(7, object.dayPassExpiresAt?.millisecondsSinceEpoch);
          fbb.addBool(8, object.isPremiumCached);
          fbb.addBool(9, object.hasMigratedToCloud);
          fbb.addOffset(10, themeModeOffset);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final installDateValue =
              const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 10);
          final lastAdWatchedAtValue =
              const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 12);
          final offlineGracePeriodStartValue =
              const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 16);
          final dayPassExpiresAtValue =
              const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 18);
          final object = AuthSettingsModel()
            ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
            ..hasSeenOnboarding =
                const fb.BoolReader().vTableGet(buffer, rootOffset, 6, false)
            ..isGuestMode =
                const fb.BoolReader().vTableGet(buffer, rootOffset, 8, false)
            ..installDate = installDateValue == null
                ? null
                : DateTime.fromMillisecondsSinceEpoch(installDateValue)
            ..lastAdWatchedAt = lastAdWatchedAtValue == null
                ? null
                : DateTime.fromMillisecondsSinceEpoch(lastAdWatchedAtValue)
            ..lastAdFailed =
                const fb.BoolReader().vTableGet(buffer, rootOffset, 14, false)
            ..offlineGracePeriodStart = offlineGracePeriodStartValue == null
                ? null
                : DateTime.fromMillisecondsSinceEpoch(
                    offlineGracePeriodStartValue)
            ..dayPassExpiresAt = dayPassExpiresAtValue == null
                ? null
                : DateTime.fromMillisecondsSinceEpoch(dayPassExpiresAtValue)
            ..isPremiumCached =
                const fb.BoolReader().vTableGet(buffer, rootOffset, 20, false)
            ..hasMigratedToCloud =
                const fb.BoolReader().vTableGet(buffer, rootOffset, 22, false)
            ..themeMode = const fb.StringReader(asciiOptimization: true)
                .vTableGet(buffer, rootOffset, 24, '');

          return object;
        }),
    CollectionModel: obx_int.EntityDefinition<CollectionModel>(
        model: _entities[2],
        toOneRelations: (CollectionModel object) => [],
        toManyRelations: (CollectionModel object) => {},
        getId: (CollectionModel object) => object.id,
        setId: (CollectionModel object, int id) {
          object.id = id;
        },
        objectToFB: (CollectionModel object, fb.Builder fbb) {
          final uidOffset = fbb.writeString(object.uid);
          final ownerIdOffset =
              object.ownerId == null ? null : fbb.writeString(object.ownerId!);
          final titleOffset = fbb.writeString(object.title);
          final categoryOffset = fbb.writeString(object.category);
          final colorHexOffset = fbb.writeString(object.colorHex);
          final iconNameOffset = fbb.writeString(object.iconName);
          final parentIdOffset = object.parentId == null
              ? null
              : fbb.writeString(object.parentId!);
          final descriptionOffset = object.description == null
              ? null
              : fbb.writeString(object.description!);
          final iconJsonOffset = object.iconJson == null
              ? null
              : fbb.writeString(object.iconJson!);
          final itemsLayoutOffset = fbb.writeString(object.itemsLayout);
          final itemsSortDefaultOffset =
              fbb.writeString(object.itemsSortDefault);
          final openLinksInOffset = fbb.writeString(object.openLinksIn);
          final childCollectionsLayoutOffset =
              fbb.writeString(object.childCollectionsLayout);
          fbb.startTable(26);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, uidOffset);
          fbb.addOffset(2, ownerIdOffset);
          fbb.addBool(3, object.isShared);
          fbb.addOffset(4, titleOffset);
          fbb.addOffset(5, categoryOffset);
          fbb.addOffset(6, colorHexOffset);
          fbb.addOffset(7, iconNameOffset);
          fbb.addFloat64(8, object.position);
          fbb.addInt64(9, object.createdAt.millisecondsSinceEpoch);
          fbb.addInt64(10, object.updatedAt.millisecondsSinceEpoch);
          fbb.addInt64(11, object.itemCount);
          fbb.addOffset(12, parentIdOffset);
          fbb.addBool(13, object.isPinned);
          fbb.addBool(14, object.isArchived);
          fbb.addBool(15, object.isDeleted);
          fbb.addInt64(16, object.childCount);
          fbb.addOffset(17, descriptionOffset);
          fbb.addOffset(18, iconJsonOffset);
          fbb.addOffset(19, itemsLayoutOffset);
          fbb.addOffset(20, itemsSortDefaultOffset);
          fbb.addOffset(21, openLinksInOffset);
          fbb.addBool(22, object.showLinkPreviews);
          fbb.addInt64(23, object.lastAccessedAt?.millisecondsSinceEpoch);
          fbb.addOffset(24, childCollectionsLayoutOffset);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final lastAccessedAtValue =
              const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 50);
          final object = CollectionModel()
            ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
            ..uid = const fb.StringReader(asciiOptimization: true)
                .vTableGet(buffer, rootOffset, 6, '')
            ..ownerId = const fb.StringReader(asciiOptimization: true)
                .vTableGetNullable(buffer, rootOffset, 8)
            ..isShared =
                const fb.BoolReader().vTableGet(buffer, rootOffset, 10, false)
            ..title = const fb.StringReader(asciiOptimization: true)
                .vTableGet(buffer, rootOffset, 12, '')
            ..category = const fb.StringReader(asciiOptimization: true)
                .vTableGet(buffer, rootOffset, 14, '')
            ..colorHex = const fb.StringReader(asciiOptimization: true)
                .vTableGet(buffer, rootOffset, 16, '')
            ..iconName = const fb.StringReader(asciiOptimization: true)
                .vTableGet(buffer, rootOffset, 18, '')
            ..position =
                const fb.Float64Reader().vTableGet(buffer, rootOffset, 20, 0)
            ..createdAt = DateTime.fromMillisecondsSinceEpoch(
                const fb.Int64Reader().vTableGet(buffer, rootOffset, 22, 0))
            ..updatedAt = DateTime.fromMillisecondsSinceEpoch(
                const fb.Int64Reader().vTableGet(buffer, rootOffset, 24, 0))
            ..itemCount =
                const fb.Int64Reader().vTableGet(buffer, rootOffset, 26, 0)
            ..parentId = const fb.StringReader(asciiOptimization: true)
                .vTableGetNullable(buffer, rootOffset, 28)
            ..isPinned =
                const fb.BoolReader().vTableGet(buffer, rootOffset, 30, false)
            ..isArchived =
                const fb.BoolReader().vTableGet(buffer, rootOffset, 32, false)
            ..isDeleted =
                const fb.BoolReader().vTableGet(buffer, rootOffset, 34, false)
            ..childCount =
                const fb.Int64Reader().vTableGet(buffer, rootOffset, 36, 0)
            ..description = const fb.StringReader(asciiOptimization: true)
                .vTableGetNullable(buffer, rootOffset, 38)
            ..iconJson = const fb.StringReader(asciiOptimization: true)
                .vTableGetNullable(buffer, rootOffset, 40)
            ..itemsLayout = const fb.StringReader(asciiOptimization: true)
                .vTableGet(buffer, rootOffset, 42, '')
            ..itemsSortDefault = const fb.StringReader(asciiOptimization: true)
                .vTableGet(buffer, rootOffset, 44, '')
            ..openLinksIn = const fb.StringReader(asciiOptimization: true)
                .vTableGet(buffer, rootOffset, 46, '')
            ..showLinkPreviews =
                const fb.BoolReader().vTableGet(buffer, rootOffset, 48, false)
            ..lastAccessedAt = lastAccessedAtValue == null
                ? null
                : DateTime.fromMillisecondsSinceEpoch(lastAccessedAtValue)
            ..childCollectionsLayout =
                const fb.StringReader(asciiOptimization: true)
                    .vTableGet(buffer, rootOffset, 52, '');

          return object;
        }),
    ItemModel: obx_int.EntityDefinition<ItemModel>(
        model: _entities[3],
        toOneRelations: (ItemModel object) => [object.collection],
        toManyRelations: (ItemModel object) => {},
        getId: (ItemModel object) => object.id,
        setId: (ItemModel object, int id) {
          object.id = id;
        },
        objectToFB: (ItemModel object, fb.Builder fbb) {
          final uidOffset = fbb.writeString(object.uid);
          final ownerIdOffset =
              object.ownerId == null ? null : fbb.writeString(object.ownerId!);
          final titleOffset = fbb.writeString(object.title);
          final descriptionOffset = object.description == null
              ? null
              : fbb.writeString(object.description!);
          final imagePathOffset = object.imagePath == null
              ? null
              : fbb.writeString(object.imagePath!);
          final imageUrlOffset = object.imageUrl == null
              ? null
              : fbb.writeString(object.imageUrl!);
          final linkOffset =
              object.link == null ? null : fbb.writeString(object.link!);
          final tagsOffset =
              object.tags == null ? null : fbb.writeString(object.tags!);
          final collectionUidOffset = fbb.writeString(object.collectionUid);
          final annotationOffset = object.annotation == null
              ? null
              : fbb.writeString(object.annotation!);
          final faviconUrlOffset = object.faviconUrl == null
              ? null
              : fbb.writeString(object.faviconUrl!);
          final dominantColorOffset = object.dominantColor == null
              ? null
              : fbb.writeString(object.dominantColor!);
          final siteNameOffset = object.siteName == null
              ? null
              : fbb.writeString(object.siteName!);
          final canonicalUrlOffset = object.canonicalUrl == null
              ? null
              : fbb.writeString(object.canonicalUrl!);
          final contentTypeOffset = object.contentType == null
              ? null
              : fbb.writeString(object.contentType!);
          final openLinksInOverrideOffset = object.openLinksInOverride == null
              ? null
              : fbb.writeString(object.openLinksInOverride!);
          fbb.startTable(31);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, uidOffset);
          fbb.addOffset(2, ownerIdOffset);
          fbb.addOffset(3, titleOffset);
          fbb.addOffset(4, descriptionOffset);
          fbb.addOffset(5, imagePathOffset);
          fbb.addOffset(6, imageUrlOffset);
          fbb.addOffset(7, linkOffset);
          fbb.addOffset(9, tagsOffset);
          fbb.addInt64(11, object.dbStatus);
          fbb.addOffset(12, collectionUidOffset);
          fbb.addFloat64(13, object.position);
          fbb.addInt64(14, object.createdAt.millisecondsSinceEpoch);
          fbb.addInt64(15, object.updatedAt.millisecondsSinceEpoch);
          fbb.addInt64(16, object.collection.targetId);
          fbb.addOffset(17, annotationOffset);
          fbb.addOffset(18, faviconUrlOffset);
          fbb.addOffset(19, dominantColorOffset);
          fbb.addOffset(20, siteNameOffset);
          fbb.addOffset(21, canonicalUrlOffset);
          fbb.addOffset(22, contentTypeOffset);
          fbb.addInt64(23, object.publishedAt?.millisecondsSinceEpoch);
          fbb.addBool(24, object.isPinned);
          fbb.addInt64(25, object.clickCount);
          fbb.addInt64(26, object.lastAccessedAt?.millisecondsSinceEpoch);
          fbb.addBool(27, object.isDeleted);
          fbb.addInt64(28, object.deletedAt?.millisecondsSinceEpoch);
          fbb.addOffset(29, openLinksInOverrideOffset);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final publishedAtValue =
              const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 50);
          final lastAccessedAtValue =
              const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 56);
          final deletedAtValue =
              const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 60);
          final object = ItemModel()
            ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
            ..uid = const fb.StringReader(asciiOptimization: true)
                .vTableGet(buffer, rootOffset, 6, '')
            ..ownerId = const fb.StringReader(asciiOptimization: true)
                .vTableGetNullable(buffer, rootOffset, 8)
            ..title = const fb.StringReader(asciiOptimization: true)
                .vTableGet(buffer, rootOffset, 10, '')
            ..description = const fb.StringReader(asciiOptimization: true)
                .vTableGetNullable(buffer, rootOffset, 12)
            ..imagePath = const fb.StringReader(asciiOptimization: true)
                .vTableGetNullable(buffer, rootOffset, 14)
            ..imageUrl = const fb.StringReader(asciiOptimization: true)
                .vTableGetNullable(buffer, rootOffset, 16)
            ..link = const fb.StringReader(asciiOptimization: true)
                .vTableGetNullable(buffer, rootOffset, 18)
            ..tags = const fb.StringReader(asciiOptimization: true)
                .vTableGetNullable(buffer, rootOffset, 22)
            ..dbStatus =
                const fb.Int64Reader().vTableGet(buffer, rootOffset, 26, 0)
            ..collectionUid = const fb.StringReader(asciiOptimization: true)
                .vTableGet(buffer, rootOffset, 28, '')
            ..position =
                const fb.Float64Reader().vTableGet(buffer, rootOffset, 30, 0)
            ..createdAt = DateTime.fromMillisecondsSinceEpoch(
                const fb.Int64Reader().vTableGet(buffer, rootOffset, 32, 0))
            ..updatedAt = DateTime.fromMillisecondsSinceEpoch(
                const fb.Int64Reader().vTableGet(buffer, rootOffset, 34, 0))
            ..annotation = const fb.StringReader(asciiOptimization: true)
                .vTableGetNullable(buffer, rootOffset, 38)
            ..faviconUrl = const fb.StringReader(asciiOptimization: true)
                .vTableGetNullable(buffer, rootOffset, 40)
            ..dominantColor = const fb.StringReader(asciiOptimization: true)
                .vTableGetNullable(buffer, rootOffset, 42)
            ..siteName = const fb.StringReader(asciiOptimization: true)
                .vTableGetNullable(buffer, rootOffset, 44)
            ..canonicalUrl = const fb.StringReader(asciiOptimization: true)
                .vTableGetNullable(buffer, rootOffset, 46)
            ..contentType = const fb.StringReader(asciiOptimization: true)
                .vTableGetNullable(buffer, rootOffset, 48)
            ..publishedAt = publishedAtValue == null
                ? null
                : DateTime.fromMillisecondsSinceEpoch(publishedAtValue)
            ..isPinned =
                const fb.BoolReader().vTableGet(buffer, rootOffset, 52, false)
            ..clickCount =
                const fb.Int64Reader().vTableGet(buffer, rootOffset, 54, 0)
            ..lastAccessedAt = lastAccessedAtValue == null
                ? null
                : DateTime.fromMillisecondsSinceEpoch(lastAccessedAtValue)
            ..isDeleted =
                const fb.BoolReader().vTableGet(buffer, rootOffset, 58, false)
            ..deletedAt = deletedAtValue == null
                ? null
                : DateTime.fromMillisecondsSinceEpoch(deletedAtValue)
            ..openLinksInOverride =
                const fb.StringReader(asciiOptimization: true)
                    .vTableGetNullable(buffer, rootOffset, 62);
          object.collection.targetId =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 36, 0);
          object.collection.attach(store);
          return object;
        }),
    SearchHistoryModel: obx_int.EntityDefinition<SearchHistoryModel>(
        model: _entities[4],
        toOneRelations: (SearchHistoryModel object) => [],
        toManyRelations: (SearchHistoryModel object) => {},
        getId: (SearchHistoryModel object) => object.id,
        setId: (SearchHistoryModel object, int id) {
          object.id = id;
        },
        objectToFB: (SearchHistoryModel object, fb.Builder fbb) {
          final queryOffset = fbb.writeString(object.query);
          fbb.startTable(4);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, queryOffset);
          fbb.addInt64(2, object.searchedAt.millisecondsSinceEpoch);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final idParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
          final queryParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 6, '');
          final searchedAtParam = DateTime.fromMillisecondsSinceEpoch(
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 8, 0));
          final object = SearchHistoryModel(
              id: idParam, query: queryParam, searchedAt: searchedAtParam);

          return object;
        })
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [AppSettingsModel] entity fields to define ObjectBox queries.
class AppSettingsModel_ {
  /// See [AppSettingsModel.id].
  static final id =
      obx.QueryIntegerProperty<AppSettingsModel>(_entities[0].properties[0]);

  /// See [AppSettingsModel.lastAdWatch].
  static final lastAdWatch =
      obx.QueryDateProperty<AppSettingsModel>(_entities[0].properties[1]);

  /// See [AppSettingsModel.isPremium].
  static final isPremium =
      obx.QueryBooleanProperty<AppSettingsModel>(_entities[0].properties[2]);

  /// See [AppSettingsModel.hasMigratedToCloud].
  static final hasMigratedToCloud =
      obx.QueryBooleanProperty<AppSettingsModel>(_entities[0].properties[3]);

  /// See [AppSettingsModel.dbThemeMode].
  static final dbThemeMode =
      obx.QueryIntegerProperty<AppSettingsModel>(_entities[0].properties[4]);
}

/// [AuthSettingsModel] entity fields to define ObjectBox queries.
class AuthSettingsModel_ {
  /// See [AuthSettingsModel.id].
  static final id =
      obx.QueryIntegerProperty<AuthSettingsModel>(_entities[1].properties[0]);

  /// See [AuthSettingsModel.hasSeenOnboarding].
  static final hasSeenOnboarding =
      obx.QueryBooleanProperty<AuthSettingsModel>(_entities[1].properties[1]);

  /// See [AuthSettingsModel.isGuestMode].
  static final isGuestMode =
      obx.QueryBooleanProperty<AuthSettingsModel>(_entities[1].properties[2]);

  /// See [AuthSettingsModel.installDate].
  static final installDate =
      obx.QueryDateProperty<AuthSettingsModel>(_entities[1].properties[3]);

  /// See [AuthSettingsModel.lastAdWatchedAt].
  static final lastAdWatchedAt =
      obx.QueryDateProperty<AuthSettingsModel>(_entities[1].properties[4]);

  /// See [AuthSettingsModel.lastAdFailed].
  static final lastAdFailed =
      obx.QueryBooleanProperty<AuthSettingsModel>(_entities[1].properties[5]);

  /// See [AuthSettingsModel.offlineGracePeriodStart].
  static final offlineGracePeriodStart =
      obx.QueryDateProperty<AuthSettingsModel>(_entities[1].properties[6]);

  /// See [AuthSettingsModel.dayPassExpiresAt].
  static final dayPassExpiresAt =
      obx.QueryDateProperty<AuthSettingsModel>(_entities[1].properties[7]);

  /// See [AuthSettingsModel.isPremiumCached].
  static final isPremiumCached =
      obx.QueryBooleanProperty<AuthSettingsModel>(_entities[1].properties[8]);

  /// See [AuthSettingsModel.hasMigratedToCloud].
  static final hasMigratedToCloud =
      obx.QueryBooleanProperty<AuthSettingsModel>(_entities[1].properties[9]);

  /// See [AuthSettingsModel.themeMode].
  static final themeMode =
      obx.QueryStringProperty<AuthSettingsModel>(_entities[1].properties[10]);
}

/// [CollectionModel] entity fields to define ObjectBox queries.
class CollectionModel_ {
  /// See [CollectionModel.id].
  static final id =
      obx.QueryIntegerProperty<CollectionModel>(_entities[2].properties[0]);

  /// See [CollectionModel.uid].
  static final uid =
      obx.QueryStringProperty<CollectionModel>(_entities[2].properties[1]);

  /// See [CollectionModel.ownerId].
  static final ownerId =
      obx.QueryStringProperty<CollectionModel>(_entities[2].properties[2]);

  /// See [CollectionModel.isShared].
  static final isShared =
      obx.QueryBooleanProperty<CollectionModel>(_entities[2].properties[3]);

  /// See [CollectionModel.title].
  static final title =
      obx.QueryStringProperty<CollectionModel>(_entities[2].properties[4]);

  /// See [CollectionModel.category].
  static final category =
      obx.QueryStringProperty<CollectionModel>(_entities[2].properties[5]);

  /// See [CollectionModel.colorHex].
  static final colorHex =
      obx.QueryStringProperty<CollectionModel>(_entities[2].properties[6]);

  /// See [CollectionModel.iconName].
  static final iconName =
      obx.QueryStringProperty<CollectionModel>(_entities[2].properties[7]);

  /// See [CollectionModel.position].
  static final position =
      obx.QueryDoubleProperty<CollectionModel>(_entities[2].properties[8]);

  /// See [CollectionModel.createdAt].
  static final createdAt =
      obx.QueryDateProperty<CollectionModel>(_entities[2].properties[9]);

  /// See [CollectionModel.updatedAt].
  static final updatedAt =
      obx.QueryDateProperty<CollectionModel>(_entities[2].properties[10]);

  /// See [CollectionModel.itemCount].
  static final itemCount =
      obx.QueryIntegerProperty<CollectionModel>(_entities[2].properties[11]);

  /// See [CollectionModel.parentId].
  static final parentId =
      obx.QueryStringProperty<CollectionModel>(_entities[2].properties[12]);

  /// See [CollectionModel.isPinned].
  static final isPinned =
      obx.QueryBooleanProperty<CollectionModel>(_entities[2].properties[13]);

  /// See [CollectionModel.isArchived].
  static final isArchived =
      obx.QueryBooleanProperty<CollectionModel>(_entities[2].properties[14]);

  /// See [CollectionModel.isDeleted].
  static final isDeleted =
      obx.QueryBooleanProperty<CollectionModel>(_entities[2].properties[15]);

  /// See [CollectionModel.childCount].
  static final childCount =
      obx.QueryIntegerProperty<CollectionModel>(_entities[2].properties[16]);

  /// See [CollectionModel.description].
  static final description =
      obx.QueryStringProperty<CollectionModel>(_entities[2].properties[17]);

  /// See [CollectionModel.iconJson].
  static final iconJson =
      obx.QueryStringProperty<CollectionModel>(_entities[2].properties[18]);

  /// See [CollectionModel.itemsLayout].
  static final itemsLayout =
      obx.QueryStringProperty<CollectionModel>(_entities[2].properties[19]);

  /// See [CollectionModel.itemsSortDefault].
  static final itemsSortDefault =
      obx.QueryStringProperty<CollectionModel>(_entities[2].properties[20]);

  /// See [CollectionModel.openLinksIn].
  static final openLinksIn =
      obx.QueryStringProperty<CollectionModel>(_entities[2].properties[21]);

  /// See [CollectionModel.showLinkPreviews].
  static final showLinkPreviews =
      obx.QueryBooleanProperty<CollectionModel>(_entities[2].properties[22]);

  /// See [CollectionModel.lastAccessedAt].
  static final lastAccessedAt =
      obx.QueryDateProperty<CollectionModel>(_entities[2].properties[23]);

  /// See [CollectionModel.childCollectionsLayout].
  static final childCollectionsLayout =
      obx.QueryStringProperty<CollectionModel>(_entities[2].properties[24]);
}

/// [ItemModel] entity fields to define ObjectBox queries.
class ItemModel_ {
  /// See [ItemModel.id].
  static final id =
      obx.QueryIntegerProperty<ItemModel>(_entities[3].properties[0]);

  /// See [ItemModel.uid].
  static final uid =
      obx.QueryStringProperty<ItemModel>(_entities[3].properties[1]);

  /// See [ItemModel.ownerId].
  static final ownerId =
      obx.QueryStringProperty<ItemModel>(_entities[3].properties[2]);

  /// See [ItemModel.title].
  static final title =
      obx.QueryStringProperty<ItemModel>(_entities[3].properties[3]);

  /// See [ItemModel.description].
  static final description =
      obx.QueryStringProperty<ItemModel>(_entities[3].properties[4]);

  /// See [ItemModel.imagePath].
  static final imagePath =
      obx.QueryStringProperty<ItemModel>(_entities[3].properties[5]);

  /// See [ItemModel.imageUrl].
  static final imageUrl =
      obx.QueryStringProperty<ItemModel>(_entities[3].properties[6]);

  /// See [ItemModel.link].
  static final link =
      obx.QueryStringProperty<ItemModel>(_entities[3].properties[7]);

  /// See [ItemModel.tags].
  static final tags =
      obx.QueryStringProperty<ItemModel>(_entities[3].properties[8]);

  /// See [ItemModel.dbStatus].
  static final dbStatus =
      obx.QueryIntegerProperty<ItemModel>(_entities[3].properties[9]);

  /// See [ItemModel.collectionUid].
  static final collectionUid =
      obx.QueryStringProperty<ItemModel>(_entities[3].properties[10]);

  /// See [ItemModel.position].
  static final position =
      obx.QueryDoubleProperty<ItemModel>(_entities[3].properties[11]);

  /// See [ItemModel.createdAt].
  static final createdAt =
      obx.QueryDateProperty<ItemModel>(_entities[3].properties[12]);

  /// See [ItemModel.updatedAt].
  static final updatedAt =
      obx.QueryDateProperty<ItemModel>(_entities[3].properties[13]);

  /// See [ItemModel.collection].
  static final collection = obx.QueryRelationToOne<ItemModel, CollectionModel>(
      _entities[3].properties[14]);

  /// See [ItemModel.annotation].
  static final annotation =
      obx.QueryStringProperty<ItemModel>(_entities[3].properties[15]);

  /// See [ItemModel.faviconUrl].
  static final faviconUrl =
      obx.QueryStringProperty<ItemModel>(_entities[3].properties[16]);

  /// See [ItemModel.dominantColor].
  static final dominantColor =
      obx.QueryStringProperty<ItemModel>(_entities[3].properties[17]);

  /// See [ItemModel.siteName].
  static final siteName =
      obx.QueryStringProperty<ItemModel>(_entities[3].properties[18]);

  /// See [ItemModel.canonicalUrl].
  static final canonicalUrl =
      obx.QueryStringProperty<ItemModel>(_entities[3].properties[19]);

  /// See [ItemModel.contentType].
  static final contentType =
      obx.QueryStringProperty<ItemModel>(_entities[3].properties[20]);

  /// See [ItemModel.publishedAt].
  static final publishedAt =
      obx.QueryDateProperty<ItemModel>(_entities[3].properties[21]);

  /// See [ItemModel.isPinned].
  static final isPinned =
      obx.QueryBooleanProperty<ItemModel>(_entities[3].properties[22]);

  /// See [ItemModel.clickCount].
  static final clickCount =
      obx.QueryIntegerProperty<ItemModel>(_entities[3].properties[23]);

  /// See [ItemModel.lastAccessedAt].
  static final lastAccessedAt =
      obx.QueryDateProperty<ItemModel>(_entities[3].properties[24]);

  /// See [ItemModel.isDeleted].
  static final isDeleted =
      obx.QueryBooleanProperty<ItemModel>(_entities[3].properties[25]);

  /// See [ItemModel.deletedAt].
  static final deletedAt =
      obx.QueryDateProperty<ItemModel>(_entities[3].properties[26]);

  /// See [ItemModel.openLinksInOverride].
  static final openLinksInOverride =
      obx.QueryStringProperty<ItemModel>(_entities[3].properties[27]);
}

/// [SearchHistoryModel] entity fields to define ObjectBox queries.
class SearchHistoryModel_ {
  /// See [SearchHistoryModel.id].
  static final id =
      obx.QueryIntegerProperty<SearchHistoryModel>(_entities[4].properties[0]);

  /// See [SearchHistoryModel.query].
  static final query =
      obx.QueryStringProperty<SearchHistoryModel>(_entities[4].properties[1]);

  /// See [SearchHistoryModel.searchedAt].
  static final searchedAt =
      obx.QueryDateProperty<SearchHistoryModel>(_entities[4].properties[2]);
}
